# Generated by Django 3.2.8 on 2021-11-18 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('c_email', models.CharField(max_length=50)),
                ('c_password', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('c_tel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_email', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=100)),
                ('e_age', models.IntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=50)),
                ('e_tel', models.CharField(max_length=50)),
                ('e_password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('manager_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('m_age', models.IntegerField(max_length=4)),
                ('manager_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.customer')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_qty', models.CharField(max_length=100)),
                ('manager_id', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.manager')),
                ('service_id', models.ForeignKey(db_column='sercice_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.service')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('time', models.TimeField()),
                ('sch_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.customer')),
            ],
        ),
        migrations.CreateModel(
            name='employee_schedule',
            fields=[
                ('e_sch_id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('manager_id', models.ForeignKey(db_column='manage_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.manager')),
                ('sch_id', models.ForeignKey(db_column='sch_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.manager'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sch_id',
            field=models.ForeignKey(db_column='sch_id', on_delete=django.db.models.deletion.CASCADE, to='johnxinasalon2.schedule'),
        ),
    ]
